### ISSUE TITLE
Change the filename

### ISSUE THREAD

**Issue by Bhushan85** [edspencer/Ext.ux.Exporter#3]
Hi edspencer,

I was wondering where do you create the file name for the export and is it possible to change it.

thanks

**Comment by edspencer** [comment]
Unfortunately I don't think this can be changed as it comes off the encoded data string

**Comment by Bhushan85** [comment]
Thanks for the prompt reply
Could you point me to the line and let me have a look because the system in here detects it as corrupted file and doesnt even ad the .xls extension when trying to save.

**Comment by edspencer** [comment]
I believe the code you are referring to is at http://github.com/edspencer/Ext.ux.Exporter/blob/master/Button.js#L40 - it's just the data uri encoding that's providing that file name and I never found a way to override it. This approach wasn't the original intended use for data uri so it may not even be possible.

**Comment by Bhushan85** [comment]
Ok not a problem.
Thanks a lot for all your help.
