### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by stotes** [edspencer/Ext.ux.Exporter#8]
I was unable to get the example to export a working file.

Neither Excel or Open Office could open the xls file.

Excel gives me this message:

 Problems came up in the following ares during load:
*Uknown
*Style

Checking the Excel log files have shown this:

XML ERROR in ExcelWorkbook description
REASON: Missing Tag
FILE:   download.xls:users:stotes:desktop:download.xls
GROUP:  Styles
TAG:    Style
ATTRIB: ID

Open office wants to import as a text file and shows the same errors.

I have attempted to export with:
Chrome 12
Firefox 3.6 - 5.1
Safari 4 - 5.1

Strangely enough I was able to use this extension in my application roughly 6 months ago without issues.

Any help would be most appreciated.

**Comment by apemberton** [comment]
@stotes did you ever get this working? seeing the same error.

**Comment by stotes** [comment]
@apemberton No unfortunately I've still been unable to get this working.
As a temporary solution I have been instruction my staff to copy and paste from the grid to excel. (Using another ux)

If you find a working "proper" solution I would be grateful if you would share it with me.
